version: "3.9"
services:
  connext_watchtower:
    restart: always 
    image: ghcr.io/hydra-net/hydranet-watchtowers/connext_watchtower:latest
    ports:
      - "8443:8443"
    volumes:
      - /root/connext_watchtower/:/connext_watchtower
      - ${PWD}/config.yaml:/connext_watchtower/config.yaml
    environment:
      - CONNEXT_CONFIG_FILE_PATH=/connext_watchtower/config.yaml
  lnd:
    restart: always 
    image: lightninglabs/lnd:v0.15.5-beta
    ports:
      - 9911:9911
    volumes:
      - ${PWD}/lnd.conf:/root/.lnd/lnd.conf
    #entrypoint: "cat /root/.lnd/lnd.conf"
    entrypoint: "lnd -C /root/.lnd/lnd.conf"